### ISSUE TITLE
Mageblood Potion and Nightfin Soup are treated as if only one of them can be active at a time

### ISSUE THREAD

**Issue by pajlada** [Ghostjs123/BuffCheck3#6]
When popping a Mageblood Potion, the Nightfin Soup icon is removed.

I believe this has to do with Nightfin Soup causing the [**Mana Regeneration**](https://classic.wowhead.com/spell=18194/mana-regeneration) buff to activate, and Mageblood Potion also causing a different [**Mana Regeneration**](https://classic.wowhead.com/spell=24363/mana-regeneration) buff.

Issue seems to be two-fold:
1) If the user has the Nightfin Soup buff active, the BuffCheck3.lua:783 check is causing Mageblood Potion to not show up because the buff name is identical
2) If the user has the Mageblood Option buff active, the BuffCheck3.lua:772 check is causing Nightfin Soup to not show up because `Mana Regeneration` is listed as a food buff

**Comment by Ghostjs123** [comment]
Thanks for the report, I knew this was happening but never made time to fix it. The correct fix is to switch everything to spell ids instead of checking the name of the buff but I don't want to break something else atm.

For now, I added a check in IsBuffPresent and another in IsFoodBuffPresent. These will double check the spell ids if the name of the buff is "Mana Regeneration".

From my brief testing with Nightfin Soup, Mageblood Potion is staying on the bar, and Nightfin's 5min/2min warnings are working correctly. If I remember I'll test Magebloods interactions when I next raid on my druid (saturdays).

Pushing the quick fix, I'll update curseforge as well after double checking mageblood. Thanks again for the help!

**Comment by pajlada** [comment]
Awesome! If you haven't gotten a release out by Sunday I'll try the git version out myself and report back :heart: Thank you!

**Comment by Ghostjs123** [comment]
The quick fix appears to be working for me, I pushed it to this repo and curseforge. I think the overwolf client should already have the new update. Let me know if theres any other issues. Feel free to close this if its working on your end, thanks!

**Comment by pajlada** [comment]
@Ghostjs123 Got to try it out today, works great! Thanks a lot for the quick fix
