### ISSUE TITLE
Suggestion: Option to add a "glow" on consumable, when buff is missing in raid or combat

### ISSUE THREAD

**Issue by pedro-cf** [Ghostjs123/BuffCheck3#7]
Suggestion: Option to add a "glow" on consumable, when buff is missing in raid or combat

**Comment by Ghostjs123** [comment]
I'm busy this week with finals. 
When I have time I'll make an options UI and add '/bc options'. I'll add the option "glow in raid" and a few others options into that new frame.

**Comment by Ghostjs123** [comment]
Hey @pedro-cf, I finished the '/bc options' frame and added a couple suggestions including the glow to it.
For the glow I found this addon https://www.curseforge.com/wow/addons/cool-glow. I ripped LibStub and LibCustomGlow out of it to get my glow working.
I'm gonna test this in two raids (Tues/Fri) before pushing it to Curse since its a larger change. Let me know if you see this and get a chance to find bugs as well.
Thanks!
